line profiling: sample.interval=20000
#File 1: ~/R/gin/gp_functions.R
#File 2: ~/R/gin/gp_test1.R
"outer" 1#199 "matrix.tau" 2#19 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 2#20 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 2#20 "eval" "eval" "withVisible" "source" 
"as.vector" "all.equal.numeric" "all.equal" "isSymmetric.matrix" "isSymmetric" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"all.equal.numeric" "all.equal" "isSymmetric.matrix" "isSymmetric" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
"%*%" "<Anonymous>" 2#24 "eval" "eval" "withVisible" "source" 
".External" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "<Anonymous>" ".Call" "RStudioGD" ".External" "dev.hold" "plot.default" "plot" 2#28 "eval" "eval" "withVisible" "source" 
"eigen" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"eigen" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"eigen" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"eigen" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"getClassDef" "is" "callNextMethod" "loadMethod" "standardGeneric" "loadMethod" "standardGeneric" "initialize" "new" "structure" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"getClassDef" "is" "callNextMethod" "loadMethod" "standardGeneric" "loadMethod" "standardGeneric" "initialize" "new" "structure" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"getClassDef" "is" "callNextMethod" "loadMethod" "standardGeneric" "loadMethod" "standardGeneric" "initialize" "new" "structure" "<Anonymous>" 1#127 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "loglike" 1#261 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
2#2 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"all" 1#114 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
1#120 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"is.finite" 1#114 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
1#74 "%in%" 1#74 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"/" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"*" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"t.default" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"all" 1#114 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"*" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"*" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"-" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"is.finite" 1#114 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"t.default" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"-" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"is.finite" 1#114 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"t.default" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
1#120 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"diag<-" 1#120 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"/" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"/" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"is.finite" 1#114 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" "as.vector" 1#146 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"/" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#110 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"chol.default" "chol" "t" 1#140 "fn" "<Anonymous>" ".External2" "optim" 1#267 "fit.gp" 2#79 "eval" "eval" "withVisible" "source" 
"exp" 2#5 "acv" 1#382 "predict.gp" 2#85 "eval" "eval" "withVisible" "source" 
"solve.default" "solve" 1#392 "predict.gp" 2#85 "eval" "eval" "withVisible" "source" 
"%*%" "as.vector" 1#395 "predict.gp" 2#85 "eval" "eval" "withVisible" "source" 
"%*%" 1#398 "predict.gp" 2#85 "eval" "eval" "withVisible" "source" 
"%*%" 1#398 "predict.gp" 2#85 "eval" "eval" "withVisible" "source" 
"gzfile" "save" "<Anonymous>" 
"getNamespace" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
